import { useEffect, useMemo, useState } from 'react';
import { api } from './platformClient';
import { Bell, Check, ChevronRight, CircleAlert, Play, RefreshCw, Shield, Sparkles, Users, X } from 'lucide-react';

type Finding={id:string;severity:'Critical'|'High'|'Medium'|'Low';category:string;fixtureId?:string;title:string;detail:string;recommendation:string;action?:'confirm-appointment'|'publish-alert';actionLabel?:string};
type AutomationData={findings:Finding[];summary:{critical:number;high:number;medium:number;low:number;total:number};lastRun?:{id:string;createdAt:number;findings:number}};

export default function AutomationCentre({setNotice}:{setNotice:(v:string)=>void}){
  const [data,setData]=useState<AutomationData>({findings:[],summary:{critical:0,high:0,medium:0,low:0,total:0}});
  const [loading,setLoading]=useState(false); const [running,setRunning]=useState(false); const [busyId,setBusyId]=useState('');
  const load=async()=>{setLoading(true);try{const r=await api.get('/api/automation');if(r.data)setData(r.data)}catch{setNotice('Could not load Automation Centre.')}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const run=async()=>{setRunning(true);try{const r=await api.post('/api/automation/run',{});if(r.data)setData(r.data);setNotice(`Automation scan completed: ${r.data?.summary?.total||0} findings.`)}catch{setNotice('Automation scan failed.')}finally{setRunning(false)}};
  const execute=async(f:Finding)=>{if(!f.action)return;setBusyId(f.id);try{const r=await api.post('/api/automation/execute',{findingId:f.id,action:f.action});setNotice(r.data?.message||'Automation action executed.');await load()}catch(e){setNotice('Automation action could not be executed.')}finally{setBusyId('')}};
  const grouped=useMemo(()=>({critical:data.findings.filter(f=>f.severity==='Critical'),high:data.findings.filter(f=>f.severity==='High'),other:data.findings.filter(f=>f.severity==='Medium'||f.severity==='Low')}),[data.findings]);
  return <><section className='page-header'><div><p className='eyebrow'>LEAGUE OPERATING SYSTEM</p><h1>Automation Centre 4.0</h1><p className='muted'>Detect → decide → alert → recommend → execute. Deterministic rules continuously identify league exceptions and propose the safest next action.</p></div><div className='automation-actions'><button className='ghost' onClick={()=>void load()}><RefreshCw size={15}/>{loading?'Refreshing':'Refresh'}</button><button className='primary' onClick={()=>void run()}><Play size={15}/>{running?'Scanning':'Run automation scan'}</button></div></section>
    <section className='stats-grid'><div className='card stat'><div className='stat-icon'><CircleAlert/></div><div><span>Critical</span><strong>{data.summary.critical}</strong><small>immediate attention</small></div></div><div className='card stat'><div className='stat-icon'><Shield/></div><div><span>High</span><strong>{data.summary.high}</strong><small>operational blockers</small></div></div><div className='card stat'><div className='stat-icon'><Sparkles/></div><div><span>Total findings</span><strong>{data.summary.total}</strong><small>current exception scan</small></div></div><div className='card stat'><div className='stat-icon'><Check/></div><div><span>Last scan</span><strong>{data.lastRun?new Date(data.lastRun.createdAt).toLocaleTimeString('en-ZA',{hour:'2-digit',minute:'2-digit'}):'—'}</strong><small>{data.lastRun?`${data.lastRun.findings} findings recorded`:'No run recorded'}</small></div></div></section>
    <div className='dashboard-grid'><div className='card'><div className='card-head'><div><span className='label'>AUTOMATION QUEUE</span><h2>Priority exceptions</h2></div><Bell size={19}/></div>{grouped.critical.concat(grouped.high).map(f=><FindingRow key={f.id} finding={f} busy={busyId===f.id} onExecute={()=>void execute(f)}/>)}{!grouped.critical.length&&!grouped.high.length&&<div className='empty-state'><h3>No high-priority exceptions</h3><p>Run another scan after schedule, matchday or official changes.</p></div>}</div><div className='card'><div className='card-head'><div><span className='label'>RECOMMENDATION ENGINE</span><h2>Suggested next actions</h2></div><Sparkles size={19}/></div>{data.findings.slice(0,7).map(f=><div className='automation-recommendation' key={`rec-${f.id}`}><div className={`automation-severity ${f.severity.toLowerCase()}`}>{f.severity}</div><div><b>{f.title}</b><small>{f.recommendation}</small></div><ChevronRight size={15}/></div>)}{!data.findings.length&&<div className='empty-state'><h3>Nothing to recommend</h3><p>The league programme currently has no detected exceptions.</p></div>}</div></div>
    <div className='card'><div className='card-head'><div><span className='label'>AUTOMATION LOGIC</span><h2>What the engine checks</h2></div><Users size={19}/></div><div className='automation-rules'><span>Unassigned officials</span><span>Unconfirmed appointments</span><span>Venue conflicts</span><span>Team clashes</span><span>Missing team sheets</span><span>Open discipline</span><span>Postponed fixtures</span><span>Unconfirmed matchdays</span></div></div></>;
}
function FindingRow({finding,busy,onExecute}:{finding:Finding;busy:boolean;onExecute:()=>void}){return <div className='automation-finding'><div className={`automation-severity ${finding.severity.toLowerCase()}`}>{finding.severity}</div><div className='automation-finding-body'><b>{finding.title}</b><small>{finding.detail}</small><span>Recommendation: {finding.recommendation}</span></div>{finding.action&&<button className='ghost small' disabled={busy} onClick={onExecute}>{busy?'Working…':finding.actionLabel||'Execute'} </button>}</div>}
