import { useMemo, useState, type Dispatch, type SetStateAction } from 'react';
import { api } from './platformClient';
import { Bell, Check, ChevronRight, CircleAlert, Megaphone, Send, Shield, Users } from 'lucide-react';

type Communication={id:string;title:string;message:string;audience:string;audienceRef?:string;type:string;priority:'Normal'|'Important'|'Urgent';status:string;createdAt:number;publishedAt?:number;linkedType?:string;linkedId?:string;read?:boolean};
type Summary={total:number;unread:number;urgent:number};

const ALL_AUDIENCES=['All clubs','Selected club','Team / age group','Parents / members','Coaches','Match officials'];
const SCOPED_AUDIENCES=['Selected club','Team / age group','Parents / members','Coaches'];
const ALL_TYPES=['Announcement','Fixture change','Referee appointment','Payment reminder','Discipline notice','Registration update'];
const SCOPED_TYPES=['Announcement','Fixture change','Payment reminder','Registration update'];

export default function Communications({items,setItems,summary,setSummary,setNotice,role='LFA Admin'}:{items:Communication[];setItems:Dispatch<SetStateAction<Communication[]>>;summary:Summary;setSummary:Dispatch<SetStateAction<Summary>>;setNotice:(v:string)=>void;role?:string}){
  const isAdmin=role==='LFA Admin';const audiences=isAdmin?ALL_AUDIENCES:SCOPED_AUDIENCES;const types=isAdmin?ALL_TYPES:SCOPED_TYPES;
  const [publishing,setPublishing]=useState(false);const [pendingReads,setPendingReads]=useState<string[]>([]);
  const [title,setTitle]=useState('');
  const [message,setMessage]=useState('');
  const [audienceChoice,setAudience]=useState('All clubs');const audience=audiences.includes(audienceChoice)?audienceChoice:audiences[0];
  const [audienceRef,setAudienceRef]=useState('');
  const [typeChoice,setType]=useState('Announcement');const type=types.includes(typeChoice)?typeChoice:types[0];
  const [priority,setPriority]=useState<Communication['priority']>('Normal');
  const [filter,setFilter]=useState('All');
  const visible=useMemo(()=>filter==='All'?items:items.filter(i=>i.priority===filter),[items,filter]);
  const publish=async()=>{if(publishing)return;if(!title.trim()||!message.trim()||!audience){setNotice('Complete the title, message and audience before publishing.');return}if(message.trim().length>2000){setNotice('Keep the message to 2000 characters or fewer.');return}setPublishing(true);try{const result=await api.post('/api/communications',{title,message,audience,audienceRef,type,priority});setItems(prev=>[result.data,...prev]);setSummary(s=>({...s,total:s.total+1,unread:s.unread+1,urgent:s.urgent+(priority==='Urgent'?1:0)}));setTitle('');setMessage('');setAudienceRef('');setNotice('Communication published and added to the notification centre.')}catch(e){setNotice(e instanceof Error&&e.message?`Could not publish the communication: ${e.message}`:'Could not publish the communication.')}finally{setPublishing(false)}};
  const markRead=async(id:string)=>{if(pendingReads.includes(id)||items.find(i=>i.id===id)?.read)return;setPendingReads(p=>[...p,id]);try{const result=await api.post(`/api/communications/${id}/read`,{});setItems(prev=>prev.map(i=>i.id===id?{...i,read:true}:i));if(!result.data?.alreadyRead)setSummary(s=>({...s,unread:Math.max(0,s.unread-1)}));setNotice('Notification marked as read.')}catch{setNotice('Could not update notification status.')}finally{setPendingReads(p=>p.filter(x=>x!==id))}};
  return <><section className='page-header'><div><p className='eyebrow'>LEAGUE COMMUNICATIONS</p><h1>Communication & Notifications Centre</h1><p className='muted'>One controlled inbox for league announcements, fixture changes, official appointments, payment reminders and club notices.</p></div><div className='comm-summary'><span><Bell size={14}/>{summary.unread} unread</span>{summary.urgent>0&&<span className='status amber'>{summary.urgent} urgent</span>}</div></section>
    <section className='stats-grid'><div className='card stat'><div className='stat-icon'><Megaphone/></div><div><span>Published</span><strong>{summary.total}</strong><small>league communications</small></div></div><div className='card stat'><div className='stat-icon'><Bell/></div><div><span>Unread</span><strong>{summary.unread}</strong><small>awaiting member review</small></div></div><div className='card stat'><div className='stat-icon'><Shield/></div><div><span>Urgent</span><strong>{summary.urgent}</strong><small>priority alerts</small></div></div><div className='card stat'><div className='stat-icon'><Users/></div><div><span>Audience</span><strong>6</strong><small>targeting modes</small></div></div></section>
    <section className='dashboard-grid'><div className='card admin-panel'><span className='label'>COMPOSE</span><h2>Send a league communication</h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder='Title'/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder='Write the message for clubs, families or officials...'/><div className='admin-grid'><select value={audience} onChange={e=>setAudience(e.target.value)}>{audiences.map(a=><option key={a}>{a}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)}>{types.map(t=><option key={t}>{t}</option>)}</select></div>{audience!=='All clubs'&&<input value={audienceRef} onChange={e=>setAudienceRef(e.target.value)} placeholder={isAdmin?'Target reference, club or team':'Your club or team (defaults to your own)'}/>}<select value={priority} onChange={e=>setPriority(e.target.value as Communication['priority'])}><option>Normal</option><option>Important</option><option>Urgent</option></select><button className='primary' disabled={publishing} onClick={publish}><Send size={15}/>{publishing?'Publishing...':'Publish notification'}</button><small className='muted'>{message.length}/2000 characters · published immediately</small></div>
      <div className='card'><div className='card-head'><div><span className='label'>INBOX</span><h2>Notification feed</h2></div><Bell size={19}/></div><div className='filters comm-filters'>{['All','Normal','Important','Urgent'].map(v=><button className={filter===v?'filter active':'filter'} key={v} onClick={()=>setFilter(v)}>{v}</button>)}</div>{visible.map(item=><div className='communication-row' key={item.id}><div className={`comm-icon ${item.priority.toLowerCase()}`}><CircleAlert size={16}/></div><div className='comm-body'><div className='comm-title'><b>{item.title}</b><span className={`status ${item.priority==='Urgent'?'amber':item.priority==='Important'?'blue':'green'}`}>{item.priority}</span></div><p>{item.message}</p><small>{item.audience}{item.audienceRef?` · ${item.audienceRef}`:''} · {item.type} · {new Date(item.createdAt).toLocaleString('en-ZA')}</small></div><button className='ghost small' disabled={Boolean(item.read)||pendingReads.includes(item.id)} onClick={()=>markRead(item.id)}><Check size={14}/>{item.read?'Read':pendingReads.includes(item.id)?'Saving...':'Mark read'}</button></div>)}{!visible.length&&<div className='empty-state'><h3>No communications yet</h3><p>Publish the first league-wide update from the composer.</p></div>}</div></section>
    <div className='card'><div className='card-head'><div><span className='label'>DELIVERY CONTROL</span><h2>Operational links</h2></div><ChevronRight size={18}/></div><div className='roadmap-items'><span>Fixture changes</span><span>Official confirmations</span><span>Payment reminders</span><span>Discipline notices</span><span>Registration updates</span><span>Club announcements</span></div></div>
  </>;
}
