import { useMemo, useState } from 'react';
import { api } from '@appdeploy/client';
import { Bell, Check, ChevronRight, CircleAlert, Megaphone, Send, Shield, Users } from 'lucide-react';

type Communication={id:string;title:string;message:string;audience:string;audienceRef?:string;type:string;priority:'Normal'|'Important'|'Urgent';status:string;createdAt:number;publishedAt?:number;linkedType?:string;linkedId?:string};
type Summary={total:number;unread:number;urgent:number};

export default function Communications({items,setItems,summary,setSummary,setNotice}:{items:Communication[];setItems:(v:Communication[])=>void;summary:Summary;setSummary:(v:Summary)=>void;setNotice:(v:string)=>void}){
  const [title,setTitle]=useState('');
  const [message,setMessage]=useState('');
  const [audience,setAudience]=useState('All clubs');
  const [audienceRef,setAudienceRef]=useState('');
  const [type,setType]=useState('Announcement');
  const [priority,setPriority]=useState<Communication['priority']>('Normal');
  const [filter,setFilter]=useState('All');
  const visible=useMemo(()=>filter==='All'?items:items.filter(i=>i.priority===filter),[items,filter]);
  const publish=async()=>{if(!title.trim()||!message.trim()||!audience){setNotice('Complete the title, message and audience before publishing.');return}if(message.trim().length>2000){setNotice('Keep the message to 2000 characters or fewer.');return}try{const result=await api.post('/api/communications',{title,message,audience,audienceRef,type,priority});setItems([result.data,...items]);setSummary({...summary,total:summary.total+1,unread:summary.unread+1,urgent:summary.urgent+(priority==='Urgent'?1:0)});setTitle('');setMessage('');setAudienceRef('');setNotice('Communication published and added to the notification centre.')}catch{setNotice('Could not publish the communication.')}};
  const markRead=async(id:string)=>{try{await api.post(`/api/communications/${id}/read`,{readerRef:'demo-member'});setSummary({...summary,unread:Math.max(0,summary.unread-1)});setNotice('Notification marked as read.')}catch{setNotice('Could not update notification status.')}};
  return <><section className='page-header'><div><p className='eyebrow'>LEAGUE COMMUNICATIONS</p><h1>Communication & Notifications Centre</h1><p className='muted'>One controlled inbox for league announcements, fixture changes, official appointments, payment reminders and club notices.</p></div><div className='comm-summary'><span><Bell size={14}/>{summary.unread} unread</span>{summary.urgent>0&&<span className='status amber'>{summary.urgent} urgent</span>}</div></section>
    <section className='stats-grid'><div className='card stat'><div className='stat-icon'><Megaphone/></div><div><span>Published</span><strong>{summary.total}</strong><small>league communications</small></div></div><div className='card stat'><div className='stat-icon'><Bell/></div><div><span>Unread</span><strong>{summary.unread}</strong><small>awaiting member review</small></div></div><div className='card stat'><div className='stat-icon'><Shield/></div><div><span>Urgent</span><strong>{summary.urgent}</strong><small>priority alerts</small></div></div><div className='card stat'><div className='stat-icon'><Users/></div><div><span>Audience</span><strong>6</strong><small>targeting modes</small></div></div></section>
    <section className='dashboard-grid'><div className='card admin-panel'><span className='label'>COMPOSE</span><h2>Send a league communication</h2><input value={title} onChange={e=>setTitle(e.target.value)} placeholder='Title'/><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder='Write the message for clubs, families or officials...'/><div className='admin-grid'><select value={audience} onChange={e=>setAudience(e.target.value)}><option>All clubs</option><option>Selected club</option><option>Team / age group</option><option>Parents / members</option><option>Coaches</option><option>Match officials</option></select><select value={type} onChange={e=>setType(e.target.value)}><option>Announcement</option><option>Fixture change</option><option>Referee appointment</option><option>Payment reminder</option><option>Discipline notice</option><option>Registration update</option></select></div>{audience!=='All clubs'&&<input value={audienceRef} onChange={e=>setAudienceRef(e.target.value)} placeholder='Target reference, club or team'/>}<select value={priority} onChange={e=>setPriority(e.target.value as Communication['priority'])}><option>Normal</option><option>Important</option><option>Urgent</option></select><button className='primary' onClick={publish}><Send size={15}/>Publish notification</button><small className='muted'>{message.length}/2000 characters · published immediately</small></div>
      <div className='card'><div className='card-head'><div><span className='label'>INBOX</span><h2>Notification feed</h2></div><Bell size={19}/></div><div className='filters comm-filters'>{['All','Normal','Important','Urgent'].map(v=><button className={filter===v?'filter active':'filter'} key={v} onClick={()=>setFilter(v)}>{v}</button>)}</div>{visible.map(item=><div className='communication-row' key={item.id}><div className={`comm-icon ${item.priority.toLowerCase()}`}><CircleAlert size={16}/></div><div className='comm-body'><div className='comm-title'><b>{item.title}</b><span className={`status ${item.priority==='Urgent'?'amber':item.priority==='Important'?'blue':'green'}`}>{item.priority}</span></div><p>{item.message}</p><small>{item.audience}{item.audienceRef?` · ${item.audienceRef}`:''} · {item.type} · {new Date(item.createdAt).toLocaleString('en-ZA')}</small></div><button className='ghost small' onClick={()=>markRead(item.id)}><Check size={14}/>Read</button></div>)}{!visible.length&&<div className='empty-state'><h3>No communications yet</h3><p>Publish the first league-wide update from the composer.</p></div>}</div></section>
    <div className='card'><div className='card-head'><div><span className='label'>DELIVERY CONTROL</span><h2>Operational links</h2></div><ChevronRight size={18}/></div><div className='roadmap-items'><span>Fixture changes</span><span>Official confirmations</span><span>Payment reminders</span><span>Discipline notices</span><span>Registration updates</span><span>Club announcements</span></div></div>
  </>;
}
