import { useEffect, useMemo, useState } from 'react';
import { api } from '@appdeploy/client';
import { CalendarDays, Check, Flag, Shield, Trophy, Users } from 'lucide-react';

type Role = 'Supporter' | 'Manager' | 'Club' | 'LFA Admin';
type Competition = { id:string; name:string; type:'League'|'Tournament'; season:string; status:string; isActive:boolean };
type Team = { id:string; name:string; ageGroup:string; competitionId?:string };
type Player = { id:string; name:string; team:string; position:string; number:number; memberRef:string; competitionId?:string };
type Fixture = { id:string; home:string; away:string; date:string; time:string; venue:string; status:string; homeScore?:number; awayScore?:number; phase?:string; matchday?:string; competitionId?:string };
type Official = { id:string; name:string; role:string; availability:string; competitionId?:string };
type Snapshot = { role:Role; competition:Competition|null; teams:Team[]; players:Player[]; fixtures:Fixture[]; officials:Official[]; standings:Array<{name:string;played:number;won:number;drawn:number;lost:number;gf:number;ga:number;gd:number;points:number}>; summary:{teams:number;players:number;fixtures:number;completed:number;upcoming:number;officials:number;venues:number;live:number}; venues:Array<{id:string;name:string;location:string;availability:string}> };

export default function CompetitionOperations({setNotice}:{setNotice:(v:string)=>void}) {
 const [data,setData]=useState<Snapshot|null>(null); const [loading,setLoading]=useState(true); const [teamName,setTeamName]=useState(''); const [ageGroup,setAgeGroup]=useState('U14'); const [playerName,setPlayerName]=useState(''); const [playerTeam,setPlayerTeam]=useState(''); const [memberRef,setMemberRef]=useState(''); const [fixtureHome,setFixtureHome]=useState(''); const [fixtureAway,setFixtureAway]=useState(''); const [fixtureDate,setFixtureDate]=useState('2026-10-10'); const [fixtureTime,setFixtureTime]=useState('15:00'); const [fixtureVenue,setFixtureVenue]=useState('Portland Sports Ground'); const [phase,setPhase]=useState('Quarter Final'); const [busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await api.get('/api/competition-operations');setData(r.data||null);const teams=r.data?.teams||[];setPlayerTeam(p=>p||teams[0]?.name||'');setFixtureHome(h=>h||teams[0]?.name||'');setFixtureAway(a=>a||teams[1]?.name||teams[0]?.name||'')}catch{setNotice('Could not load competition operations.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const active=data?.competition; const canManage=data?.role==='LFA Admin';
 const run=async(path:string,body:Record<string,unknown>,success='Competition record saved.')=>{setBusy(true);try{const r=await api.post(path,body);setNotice(r.data?.message||success);await load()}catch{setNotice('Could not save the competition record.')}finally{setBusy(false)}};
 const grouped=useMemo(()=>{const map=new Map<string,Player[]>();(data?.players||[]).forEach(p=>map.set(p.team,[...(map.get(p.team)||[]),p]));return map},[data?.players]);
 const addTeam=()=>{if(!teamName.trim()){setNotice('Team name is required.');return}void run('/api/competition-operations/teams',{name:teamName.trim(),ageGroup},'Team registered to the active competition.').then(()=>setTeamName(''))};
 const addPlayer=()=>{if(!playerName.trim()||!playerTeam||!memberRef.trim()){setNotice('Player name, team and member reference are required.');return}void run('/api/competition-operations/players',{name:playerName.trim(),team:playerTeam,memberRef:memberRef.trim(),position:'CM',number:0},'Player registered to the active competition.').then(()=>{setPlayerName('');setMemberRef('')})};
 const addFixture=()=>{if(!fixtureHome||!fixtureAway||fixtureHome===fixtureAway){setNotice('Choose two different teams.');return}if(!fixtureDate||!fixtureTime||!fixtureVenue.trim()){setNotice('Complete date, kick-off and venue.');return}void run('/api/competition-operations/fixtures',{home:fixtureHome,away:fixtureAway,date:fixtureDate,time:fixtureTime,venue:fixtureVenue.trim(),phase:active?.type==='Tournament'?phase:'League',matchday:active?.type==='League'?`Matchday`:'Knockout'},'Competition-scoped fixture created.')};
 if(loading&&!data)return <div className='empty-state'><h3>Loading competition operations</h3><p>Loading the active competition context.</p></div>;
 if(!data)return <div className='empty-state'><h3>No competition context</h3><p>Create and activate a competition in Competition Portfolio first.</p></div>;
 return <><section className='page-header'><div><p className='eyebrow'>COMPETITION OPERATIONS 21.0</p><h1>Competition Operations Engine</h1><p className='muted'>Run the active league or tournament from one scoped workspace. Teams, players, fixtures, officials, venues and standings stay attached to the active competition.</p></div><button className='ghost' onClick={()=>void load()}><CalendarDays size={15}/>Refresh</button></section>
 <section className='card context-selector'><div><span className='label'>ACTIVE COMPETITION</span><h2>{active?.name||'No active competition'}</h2><p className='muted'>{active?`${active.type} · ${active.season} · ${active.status}`:'Activate a competition first.'}</p></div><span className='status green'>{active?.type||'—'}</span></section>
 <section className='stats-grid'><Stat icon={<Trophy/>} label='Teams' value={`${data.summary.teams}`} detail='registered in scope'/><Stat icon={<Users/>} label='Players' value={`${data.summary.players}`} detail='registered in scope'/><Stat icon={<CalendarDays/>} label='Fixtures' value={`${data.summary.fixtures}`} detail={`${data.summary.completed} completed · ${data.summary.upcoming} upcoming`}/><Stat icon={<Shield/>} label='Officials' value={`${data.summary.officials}`} detail={`${data.summary.venues} venues`}/></section>
 {canManage&&<><section className='dashboard-grid'><div className='card competition-form'><div className='card-head'><div><span className='label'>TEAM REGISTRATION</span><h2>Add team to this competition</h2></div><Users size={19}/></div><div className='competition-form-grid'><input value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder='Team name'/><select value={ageGroup} onChange={e=>setAgeGroup(e.target.value)}>{['U8','U10','U12','U14','U16','U18'].map(v=><option key={v}>{v}</option>)}</select></div><button className='primary' disabled={busy} onClick={addTeam}><Users size={15}/>Register team</button></div><div className='card competition-form'><div className='card-head'><div><span className='label'>PLAYER REGISTRATION</span><h2>Add player to this competition</h2></div><Users size={19}/></div><div className='competition-form-grid'><input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder='Player name'/><select value={playerTeam} onChange={e=>setPlayerTeam(e.target.value)}>{data.teams.map(t=><option key={t.name}>{t.name}</option>)}</select><input value={memberRef} onChange={e=>setMemberRef(e.target.value)} placeholder='Member reference'/></div><button className='primary' disabled={busy} onClick={addPlayer}><Users size={15}/>Register player</button></div></section><section className='card competition-form'><div className='card-head'><div><span className='label'>FIXTURE & MATCHDAY</span><h2>Create a competition-scoped fixture</h2></div><CalendarDays size={19}/></div><div className='competition-form-grid'><select value={fixtureHome} onChange={e=>setFixtureHome(e.target.value)}>{data.teams.map(t=><option key={`h-${t.name}`}>{t.name}</option>)}</select><select value={fixtureAway} onChange={e=>setFixtureAway(e.target.value)}>{data.teams.map(t=><option key={`a-${t.name}`}>{t.name}</option>)}</select><input type='date' value={fixtureDate} onChange={e=>setFixtureDate(e.target.value)}/><input value={fixtureTime} onChange={e=>setFixtureTime(e.target.value)} placeholder='Kick-off'/><input value={fixtureVenue} onChange={e=>setFixtureVenue(e.target.value)} placeholder='Venue'/>{active?.type==='Tournament'&&<select value={phase} onChange={e=>setPhase(e.target.value)}><option>Round of 16</option><option>Quarter Final</option><option>Semi Final</option><option>Final</option></select>}</div><button className='primary' disabled={busy} onClick={addFixture}><CalendarDays size={15}/>Create fixture</button></section></>}
 <section className='dashboard-grid'><div className='card'><div className='card-head'><div><span className='label'>{active?.type==='Tournament'?'TOURNAMENT BRACKET FEED':'LIVE LEAGUE TABLE'}</span><h2>{active?.type==='Tournament'?'Knockout programme':'Standings'}</h2></div><Flag size={19}/></div>{active?.type==='Tournament'?data.fixtures.map(f=><div className='admin-row' key={f.id}><div><b>{f.phase||'Round'} · {f.home} vs {f.away}</b><small>{f.date} · {f.time} · {f.status}</small></div><span className='status blue'>{typeof f.homeScore==='number'?`${f.homeScore}-${f.awayScore}`:'Scheduled'}</span></div>):<div className='league-table'><div className='table-row table-head'><span>#</span><span>Team</span><span>P</span><span>W</span><span>D</span><span>L</span><span>GD</span><b>Pts</b></div>{data.standings.map((t,i)=><div className='table-row' key={t.name}><span>{i+1}</span><b>{t.name}</b><span>{t.played}</span><span>{t.won}</span><span>{t.drawn}</span><span>{t.lost}</span><span>{t.gd>0?'+':''}{t.gd}</span><strong>{t.points}</strong></div>)}{!data.standings.length&&<div className='empty-state'><h3>No completed results</h3><p>Completed competition results populate the table.</p></div>}</div>}</div><div className='card'><div className='card-head'><div><span className='label'>COMPETITION ROSTER</span><h2>Teams & registered players</h2></div><Users size={19}/></div>{data.teams.slice(0,16).map(t=><div className='admin-row' key={t.id}><div><b>{t.name}</b><small>{t.ageGroup} · {(grouped.get(t.name)||[]).length} registered players</small></div><span className='status green'>Active</span></div>)}</div></section>
 <section className='dashboard-grid lower'><div className='card'><div className='card-head'><div><span className='label'>UPCOMING FIXTURES</span><h2>Matchday pipeline</h2></div><CalendarDays size={19}/></div>{data.fixtures.filter(f=>f.status!=='completed').slice(0,12).map(f=><div className='admin-row' key={f.id}><div><b>{f.home} vs {f.away}</b><small>{f.date} · {f.time} · {f.venue} · {f.matchday||f.phase||'Programme'}</small></div><span className={`status ${f.status==='Live'?'blue':'green'}`}>{f.status}</span></div>)}{!data.fixtures.filter(f=>f.status!=='completed').length&&<div className='empty-state'><h3>No upcoming fixtures</h3><p>Create the next matchday above.</p></div>}</div><div className='card'><div className='card-head'><div><span className='label'>OPERATIONAL CHECKS</span><h2>Competition readiness</h2></div><Shield size={19}/></div><Queue label='Competition isolated' detail='New records carry the active competition ID.'/><Queue label='Fixture safety' detail='Venue and team-slot conflicts are rejected.'/><Queue label='Standings linked' detail='Completed scoped results drive league points.'/><Queue label='Live match centre' detail={`${data.summary.live} live fixture(s) in this competition.`}/><Queue label='Cross-competition control' detail='Switch the active competition from Competition Context.'/></div></section></>;
}
function Stat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className='card stat'><div className='stat-icon'>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>}
function Queue({label,detail}:{label:string;detail:string}){return <div className='queue'><span className='queue-icon'><Check size={15}/></span><span><b>{label}</b><small>{detail}</small></span></div>}
