import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { api } from './platformClient';
import { CalendarDays, Check, ChevronRight, Flag, GitBranch, RefreshCw, Shield, Trophy, Users } from 'lucide-react';

type Role='Supporter'|'Manager'|'Club'|'LFA Admin';
type Competition={id:string;name:string;type:'League'|'Tournament';season:string;status:string;isActive:boolean};
type Team={id:string;name:string;ageGroup:string;clubId?:string};
type Snapshot={role:Role;competition:Competition|null;competitions:Competition[];seasons:any[];divisions:any[];groups:any[];rules:any[];brackets:any[];bracketMatches:any[];groupEntries:any[];promotionRelegation:any[];approvals:any[];fixtures:any[];teams:Team[];players:any[];officials:any[];clubs:any[];audit:any[];summary:Record<string,number>;permissions:string[]};

const blank:Snapshot={role:'Supporter',competition:null,competitions:[],seasons:[],divisions:[],groups:[],rules:[],brackets:[],bracketMatches:[],groupEntries:[],promotionRelegation:[],approvals:[],fixtures:[],teams:[],players:[],officials:[],clubs:[],audit:[],summary:{},permissions:[]};

export default function CompetitionOperations({setNotice}:{setNotice:(v:string)=>void}){
 const [data,setData]=useState<Snapshot>(blank); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [section,setSection]=useState('overview');
 const [season,setSeason]=useState('2026/27'); const [division,setDivision]=useState(''); const [group,setGroup]=useState(''); const [ageGroup,setAgeGroup]=useState('U14'); const [rules,setRules]=useState({pointsWin:3,pointsDraw:1,pointsLoss:0,matchDuration:90,halfDuration:45,substitutionLimit:5,benchLimit:7,extraTime:true,penalties:true,offside:true,cards:true,promotionPlaces:1,relegationPlaces:1,drawVerification:true});
 const [selectedTeams,setSelectedTeams]=useState<string[]>([]); const [bracketSize,setBracketSize]=useState(8); const [promotion,setPromotion]=useState(''); const [relegation,setRelegation]=useState(''); const [clubName,setClubName]=useState(''); const [teamName,setTeamName]=useState(''); const [playerName,setPlayerName]=useState(''); const [memberRef,setMemberRef]=useState(''); const [selectedTeam,setSelectedTeam]=useState(''); const [fixtureId,setFixtureId]=useState(''); const [officialId,setOfficialId]=useState(''); const [matchNote,setMatchNote]=useState('');
 const active=data.competition;
 const load=async(silent=false)=>{if(!silent)setLoading(true);try{const r=await api.get('/api/competition-platform');if(r.data){setData(r.data);const rr=r.data.rules?.[0];if(rr)setRules(v=>({...v,...rr}));const ts=r.data.teams||[];setSelectedTeam(v=>v||ts[0]?.id||'');setFixtureId(v=>v||r.data.fixtures?.[0]?.id||'');setOfficialId(v=>v||r.data.officials?.[0]?.id||'')}}catch{setNotice('Competition control data could not be loaded.')}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{void load();const timer=window.setInterval(()=>void load(true),30000);return()=>window.clearInterval(timer)},[]);
 const action=async(name:string,body:Record<string,unknown>={},success='Saved.')=>{if(!active){setNotice('Create or activate a competition first.');return}setBusy(true);try{const requestKey=`${name}:${active.id}:${Date.now()}:${Math.random().toString(36).slice(2)}`;const r=await api.post('/api/competition-platform/action',{action:name,competitionId:active.id,requestKey,...body});setNotice(r.data?.message||success);await load(true)}catch{setNotice('The operation was rejected. Check the competition rules and required fields.')}finally{setBusy(false)}};
 const addSeason=()=>void action('create-season',{name:season,startDate:'2026-09-01',endDate:'2027-06-30'});
 const addDivision=()=>{if(!division.trim())return setNotice('Enter a division name.');void action('create-division',{name:division.trim(),ageGroup,level:1}).then(()=>setDivision(''))};
 const addGroup=()=>{if(!group.trim())return setNotice('Enter a group name.');void action('create-group',{name:group.trim(),divisionId:data.divisions[0]?.id||'',stage:'Group stage'}).then(()=>setGroup(''))};
 const saveRules=()=>void action('save-rules',rules,'Competition rules saved.');
 const createBracket=()=>{if(selectedTeams.length!==bracketSize)return setNotice(`Select exactly ${bracketSize} teams.`);void action('create-bracket',{size:bracketSize,teams:selectedTeams})};
 const toggleTeam=(id:string)=>setSelectedTeams(v=>v.includes(id)?v.filter(x=>x!==id):v.length<bracketSize?[...v,id]:v);
 const firstBracket=data.bracketMatches.filter((m:any)=>Number(m.round)===1);
 const selectedRule=data.rules[0]||rules;
 const nav=[['overview','Control centre'],['structure','Seasons & groups'],['tournament','Tournament engine'],['rules','Competition rules'],['registrations','Registrations'],['matches','Match operations'],['governance','Approvals & audit']];
 if(loading&&!data.competition)return <div className='empty-state'><h3>Loading Competition Control Centre</h3><p>Synchronising competition, tournament and operational records.</p></div>;
 if(!active)return <div className='empty-state'><h3>No active competition</h3><p>Open Competition Portfolio and activate a league or tournament before managing competition operations.</p></div>;
 return <>
  <section className='page-header'><div><p className='eyebrow'>PITCHLINE COMPETITION CONTROL 25.0</p><h1>{active.name}</h1><p className='muted'>{active.type} · {active.season} · {active.status} · mobile-ready operational workspace</p></div><button className='ghost' onClick={()=>void load()}><RefreshCw size={15}/>Refresh</button></section>
  <section className='filters'>{nav.map(([id,label])=><button key={id} className={`filter ${section===id?'active':''}`} onClick={()=>setSection(id)}>{label}</button>)}</section>
  <section className='stats-grid'><Stat icon={<Trophy/>} label='Teams' value={data.summary.teams||0} detail='registered in competition'/><Stat icon={<Users/>} label='Players' value={data.summary.players||0} detail='competition registrations'/><Stat icon={<CalendarDays/>} label='Fixtures' value={data.summary.fixtures||0} detail={`${data.summary.live||0} live · ${data.summary.completed||0} completed`}/><Stat icon={<GitBranch/>} label='Tournament brackets' value={data.summary.brackets||0} detail='protected knockout structures'/></section>
  {section==='overview'&&<Overview data={data} setSection={setSection}/>} 
  {section==='structure'&&<><Panel title='Season management' icon={<CalendarDays/>}><div className='competition-form-grid'><input value={season} onChange={e=>setSeason(e.target.value)} placeholder='Season name'/><button className='primary' disabled={busy} onClick={addSeason}>Create season</button></div><List rows={data.seasons} empty='No seasons configured.' render={(x:any)=><Row title={x.name} detail={`${x.startDate||'—'} → ${x.endDate||'—'}`} tag={x.status||'Setup'}/>)}/></Panel><Panel title='Divisions' icon={<Trophy/>}><div className='competition-form-grid'><input value={division} onChange={e=>setDivision(e.target.value)} placeholder='Division name'/><select value={ageGroup} onChange={e=>setAgeGroup(e.target.value)}>{['U8','U10','U12','U14','U16','U18'].map(x=><option key={x}>{x}</option>)}</select><button className='primary' disabled={busy} onClick={addDivision}>Add division</button></div><List rows={data.divisions} empty='No divisions configured.' render={(x:any)=><Row title={x.name} detail={`${x.ageGroup} · Level ${x.level||1}`} tag={x.status||'Active'}/>)}/></Panel><Panel title='Group stages' icon={<Users/>}><div className='competition-form-grid'><input value={group} onChange={e=>setGroup(e.target.value)} placeholder='Group A / Group B'/><button className='primary' disabled={busy} onClick={addGroup}>Create group</button></div><List rows={data.groups} empty='No groups configured.' render={(x:any)=><Row title={x.name} detail={`${x.stage||'Group stage'} · ${x.teamCount||0} teams`} tag={x.status||'Setup'}/>)}/><div className='subtle-note'>Teams can be added to groups through the protected group-entry API. Duplicate team/group assignments are rejected.</div></Panel><Panel title='Promotion & relegation' icon={<ChevronRight/>}><div className='competition-form-grid'><input value={promotion} onChange={e=>setPromotion(e.target.value)} placeholder='Promoted teams, comma separated'/><input value={relegation} onChange={e=>setRelegation(e.target.value)} placeholder='Relegated teams, comma separated'/><button className='primary' disabled={busy} onClick={()=>void action('save-promotion',{divisionId:data.divisions[0]?.id||'',season:active.season,promoted:promotion.split(',').map(x=>x.trim()).filter(Boolean),relegated:relegation.split(',').map(x=>x.trim()).filter(Boolean)})}>Save structure</button></div><List rows={data.promotionRelegation} empty='No promotion/relegation structure saved.' render={(x:any)=><Row title={`${(x.promoted||[]).join(', ')||'No promoted teams'}`} detail={`Relegated: ${(x.relegated||[]).join(', ')||'None'} · ${x.season||''}`} tag={x.status||'Draft'}/>)}/></Panel></>}
  {section==='tournament'&&<><Panel title='Tournament bracket engine' icon={<GitBranch/>><div className='competition-form-grid'><select value={bracketSize} onChange={e=>setBracketSize(Number(e.target.value))}>{[4,8,16,32].map(x=><option key={x}>{x}</option>)}</select><button className='primary' disabled={busy||selectedTeams.length!==bracketSize} onClick={createBracket}>Generate {bracketSize}-team bracket</button></div><p className='muted'>The draw is generated once per active tournament. Existing active brackets cannot be duplicated. Knockout matches advance only through recorded results; verified matches become locked.</p><div className='team-picker'>{data.teams.map(t=><button key={t.id} className={`team-chip ${selectedTeams.includes(t.id)?'selected':''}`} onClick={()=>toggleTeam(t.id)}><Check size={14}/>{t.name}</button>)}</div></Panel><Panel title='Knockout rounds' icon={<Flag/>}><List rows={data.brackets} empty='No tournament bracket yet.' render={(b:any)=><Row title={`${b.size}-team knockout`} detail={`Created ${new Date(Number(b.createdAt||Date.now())).toLocaleDateString()} · ${b.roundCount} rounds`} tag={b.status||'Active'}/>)}/>{firstBracket.map((m:any)=><BracketMatch key={m.id} match={m} onSave={(winner,homeScore,awayScore,verification)=>void action('advance-bracket',{matchId:m.id,winner,homeScore,awayScore,verification})} busy={busy}/>)}</Panel></>}
  {section==='rules'&&<Panel title='Competition-specific rules' icon={<Shield/>}><div className='rule-grid'>{(['pointsWin','pointsDraw','pointsLoss','matchDuration','halfDuration','substitutionLimit','benchLimit','promotionPlaces','relegationPlaces'] as const).map(k=><label key={k}>{k.replace(/[A-Z]/g,m=>` ${m}`).replace(/^./,m=>m.toUpperCase())}<input type='number' value={Number(rules[k])} onChange={e=>setRules({...rules,[k]:Number(e.target.value)})}/></label>)}</div><div className='toggle-grid'>{(['extraTime','penalties','offside','cards','drawVerification'] as const).map(k=><label key={k}><input type='checkbox' checked={Boolean(rules[k])} onChange={e=>setRules({...rules,[k]:e.target.checked})}/>{k.replace(/[A-Z]/g,m=>` ${m}`)}</label>)}</div><button className='primary' disabled={busy} onClick={saveRules}>Save competition rules</button><div className='subtle-note'>These rules are stored against the competition and can be consumed by match operations. Draw verification is required before a drawn knockout match can advance.</div></Panel>}
  {section==='registrations'&&<><Panel title='Club registration' icon={<Users/>}><div className='competition-form-grid'><input value={clubName} onChange={e=>setClubName(e.target.value)} placeholder='Club name'/><button className='primary' disabled={busy} onClick={()=>void action('register-club',{name:clubName.trim()}).then(()=>setClubName(''))}>Register club</button></div><List rows={data.clubs.filter((x:any)=>String(x.competitionId||'')===String(active.id))} empty='No competition-specific club registrations.' render={(x:any)=><Row title={x.name} detail={x.shortName||''} tag={x.status||'Pending'}/>)}/></Panel><Panel title='Team registration' icon={<Users/>}><div className='competition-form-grid'><input value={teamName} onChange={e=>setTeamName(e.target.value)} placeholder='Team name'/><select value={ageGroup} onChange={e=>setAgeGroup(e.target.value)}>{['U8','U10','U12','U14','U16','U18'].map(x=><option key={x}>{x}</option>)}</select><button className='primary' disabled={busy} onClick={()=>void action('register-team',{name:teamName.trim(),ageGroup}).then(()=>setTeamName(''))}>Register team</button></div></Panel><Panel title='Player registration' icon={<Users/>}><div className='competition-form-grid'><input value={playerName} onChange={e=>setPlayerName(e.target.value)} placeholder='Player name'/><select value={selectedTeam} onChange={e=>setSelectedTeam(e.target.value)}>{data.teams.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input value={memberRef} onChange={e=>setMemberRef(e.target.value)} placeholder='Member reference'/><button className='primary' disabled={busy} onClick={()=>void action('register-player',{name:playerName.trim(),teamId:selectedTeam,memberRef:memberRef.trim()}).then(()=>{setPlayerName('');setMemberRef('')})}>Register player</button></div></Panel><Panel title='Post-match approvals' icon={<Check/>}><List rows={data.approvals} empty='No result approvals.' render={(x:any)=><Row title={`Fixture ${x.fixtureId}`} detail={`Approved by ${x.approvedBy||'admin'}`} tag={x.status||'Pending'}/>)}/></Panel></>}
  {section==='matches'&&<><Panel title='Match operations' icon={<CalendarDays/>}><div className='competition-form-grid'><select value={fixtureId} onChange={e=>setFixtureId(e.target.value)}>{data.fixtures.map((f:any)=><option key={f.id} value={f.id}>{f.home} vs {f.away} · {f.date}</option>)}</select><select value={officialId} onChange={e=>setOfficialId(e.target.value)}>{data.officials.map((o:any)=><option key={o.id} value={o.id}>{o.name} · {o.role}</option>)}</select><button className='primary' disabled={busy} onClick={()=>void action('add-match-official',{fixtureId,officialId,role:'Referee'})}>Assign official</button></div><textarea value={matchNote} onChange={e=>setMatchNote(e.target.value)} placeholder='Match notes, incidents, administrative notes...'/><button className='primary' disabled={busy} onClick={()=>void action('save-match-note',{fixtureId,note:matchNote.trim()}).then(()=>setMatchNote(''))}>Save match note</button></Panel><Panel title='Existing match pipeline' icon={<Flag/>}><List rows={data.fixtures} empty='No fixtures.' render={(f:any)=><Row title={`${f.home} vs ${f.away}`} detail={`${f.date} · ${f.time} · ${f.venue}`} tag={typeof f.homeScore==='number'?`${f.homeScore}-${f.awayScore}`:f.status}/>)}/><div className='subtle-note'>Starting XI, bench, substitution timestamps, goalscorer/assist, cards, injury time, half-time/full-time and the live timeline remain connected through the existing Matchday and Live Match Centres.</div></Panel></>}
  {section==='governance'&&<><Panel title='Permission boundary' icon={<Shield/>}><div className='queue'><span className='queue-icon'><Check size={15}/></span><span><b>LFA Admin control</b><small>Competition structure, tournament draws, approvals, promotion/relegation and audit operations require LFA Admin authentication.</small></span></div><div className='queue'><span className='queue-icon'><Check size={15}/></span><span><b>Public/club/manager read paths</b><small>Supporters, Clubs and Managers receive scoped read access and cannot mutate competition structure through these endpoints.</small></span></div></Panel><Panel title='Audit trail' icon={<Shield/>}><List rows={data.audit} empty='No competition audit events yet.' render={(x:any)=><Row title={x.action||'Competition operation'} detail={`${x.targetId||'—'} · ${x.actor||'system'} · ${x.createdAt?new Date(Number(x.createdAt)).toLocaleString():'—'}`} tag='Logged'/> )}/></Panel></>}
 </>;
}

function Overview({data,setSection}:{data:Snapshot;setSection:(x:string)=>void}){return <section className='dashboard-grid'><Panel title='Competition readiness' icon={<Shield/>}><Queue label='Competition isolation' detail={`${data.summary.competitions||0} competitions available; active scope is ${data.competition?.name}.`}/><Queue label='Season/division/group framework' detail={`${data.summary.seasons||0} seasons · ${data.summary.divisions||0} divisions · ${data.summary.groups||0} groups.`}/><Queue label='Tournament engine' detail={`${data.summary.brackets||0} protected bracket(s) with automatic winner routing.`}/><Queue label='Governance' detail={`${data.summary.pendingApprovals||0} pending approval(s) · ${data.summary.auditEvents||0} recent audit events.`}/></Panel><Panel title='Quick actions' icon={<ChevronRight/>}><button className='ghost full' onClick={()=>setSection('structure')}>Configure seasons, divisions and groups</button><button className='ghost full' onClick={()=>setSection('tournament')}>Build tournament bracket</button><button className='ghost full' onClick={()=>setSection('rules')}>Set competition-specific rules</button><button className='ghost full' onClick={()=>setSection('matches')}>Manage match operations</button></Panel><Panel title='Operational handoff' icon={<Flag/>}><p className='muted'>The competition control layer is now the administrative source for competition structure. Existing live match, team-sheet, standings, scheduling, discipline, club, player and supporter surfaces continue to operate through their protected APIs.</p><div className='subtle-note'>Refreshes are silent and preserve current data. The backend records idempotency keys and audit events for competition mutations.</div></Panel></section>}
function Panel({title,icon,children}:{title:string;icon:ReactNode;children:ReactNode}){return <section className='card competition-form'><div className='card-head'><div><span className='label'>{title.toUpperCase()}</span><h2>{title}</h2></div>{icon}</div>{children}</section>}
function Stat({icon,label,value,detail}:{icon:ReactNode;label:string;value:number;detail:string}){return <div className='card stat'><div className='stat-icon'>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>}
function Queue({label,detail}:{label:string;detail:string}){return <div className='queue'><span className='queue-icon'><Check size={15}/></span><span><b>{label}</b><small>{detail}</small></span></div>}
function Row({title,detail,tag}:{title:string;detail:string;tag:string}){return <div className='admin-row'><div><b>{title}</b><small>{detail}</small></div><span className='status green'>{tag}</span></div>}
function List({rows,empty,render}:{rows:any[];empty:string;render:(row:any)=>ReactNode}){if(!rows?.length)return <div className='empty-state'><h3>{empty}</h3></div>;return <div>{rows.slice(0,80).map((x:any,i)=> <div key={String(x.id||i)}>{render(x)}</div>)}</div>}
function BracketMatch({match,onSave,busy}:{match:any;onSave:(winner:string,home:number,away:number,verification:string)=>void;busy:boolean}){const [winner,setWinner]=useState(String(match.home||''));const [home,setHome]=useState('');const [away,setAway]=useState('');const [verification,setVerification]=useState('');return <div className='admin-row'><div><b>{match.home} vs {match.away}</b><small>Round {match.round} · Match {match.matchNumber} · {match.status}</small></div><div className='competition-form-grid'><select value={winner} onChange={e=>setWinner(e.target.value)}><option>{match.home}</option><option>{match.away}</option></select><input inputMode='numeric' value={home} onChange={e=>setHome(e.target.value)} placeholder='H'/><input inputMode='numeric' value={away} onChange={e=>setAway(e.target.value)} placeholder='A'/>{home===away&&home!==''&&<select value={verification} onChange={e=>setVerification(e.target.value)}><option value=''>Draw verification</option><option value='Verified'>Verified</option></select>}<button className='ghost small' disabled={busy} onClick={()=>onSave(winner,Number(home),Number(away),verification)}>Save result</button></div></div>}
