import { useEffect, useMemo, useState } from 'react';
import { api, ws } from './platformClient';
import { CalendarDays, Check, ClipboardCheck, Clock3, Flag, Home, Radio, Shield, Trophy, Users } from 'lucide-react';

type Fixture={id:string;home:string;away:string;date:string;time:string;venue:string;status:string;homeScore?:number;awayScore?:number;matchdayStatus?:string};
type Appointment={id:string;fixtureId:string;officialId:string;role:string;status:string};
type TeamSheet={id:string;fixtureId:string;formation:string;captainRef:string;starters:string[];substitutes:string[];attendance:string[]};
type Readiness={id?:string;fixtureId:string;venueReady:boolean;officialsReady:boolean;teamSheetReady:boolean;resultReady:boolean;notes:string;updatedAt:number};
type Command={fixtures:Fixture[];appointments:Appointment[];teamSheets:TeamSheet[];readiness:Readiness[];disciplineCount:number;performanceCount:number};
type Props={role:string;setNotice:(v:string)=>void};
const statuses=['Planned','Confirmed','Live','Half time','Full time'];

export default function MatchdayCommandCentre({role,setNotice}:Props){
 const [data,setData]=useState<Command>({fixtures:[],appointments:[],teamSheets:[],readiness:[],disciplineCount:0,performanceCount:0});
 const [selectedId,setSelectedId]=useState('');
 const [busy,setBusy]=useState(false);
 const [status,setStatus]=useState('Confirmed');
 const [scores,setScores]=useState({home:'',away:''});
 const [ready,setReady]=useState<Readiness>({fixtureId:'',venueReady:false,officialsReady:false,teamSheetReady:false,resultReady:false,notes:'',updatedAt:0});
 const canManage=role==='LFA Admin';
 const load=async()=>{try{const r=await api.get('/api/matchday-command');if(r.data)setData(r.data)}catch{setNotice('Could not load the matchday command centre.')}};
 useEffect(()=>{void load();const c=ws.connect();c.onMessage(m=>{if(m?.type==='entity.update'&&m.payload?.entity_type==='matchday-command'&&m.payload?.data)setData(m.payload.data)});c.ready.then(()=>{if(c.connectionId)void api.post('/api/subscriptions',{entity_type:'matchday-command',entity_id:'league',connection_id:c.connectionId})}).catch(()=>undefined);return()=>c.disconnect()},[]);
 const fixtures=useMemo(()=>data.fixtures.filter(f=>f.status!=='completed').sort((a,b)=>`${a.date}${a.time}`.localeCompare(`${b.date}${b.time}`)),[data.fixtures]);
 const selected=fixtures.find(f=>f.id===selectedId)||fixtures[0];
 const appointments=data.appointments.filter(a=>a.fixtureId===selected?.id);
 const sheet=data.teamSheets.find(s=>s.fixtureId===selected?.id);
 const existing=data.readiness.find(r=>r.fixtureId===selected?.id);
 const exceptions=fixtures.filter(f=>f.matchdayStatus!=='Confirmed'||!data.appointments.some(a=>a.fixtureId===f.id&&a.status!=='Declined')||!data.teamSheets.some(s=>s.fixtureId===f.id));
 useEffect(()=>{if(!selected)return;setReady(existing||{fixtureId:selected.id,venueReady:selected.matchdayStatus==='Confirmed',officialsReady:appointments.length>0,teamSheetReady:Boolean(sheet),resultReady:false,notes:'',updatedAt:0});setStatus(selected.matchdayStatus||'Planned');setScores({home:typeof selected.homeScore==='number'?String(selected.homeScore):'',away:typeof selected.awayScore==='number'?String(selected.awayScore):''})},[selected?.id,existing?.updatedAt,sheet?.id,appointments.length]);
 const saveReadiness=async()=>{if(!selected||!canManage)return;setBusy(true);try{const r=await api.post('/api/matchday-readiness',ready);setReady(r.data);setNotice('Matchday readiness saved.')}catch{setNotice('Could not save matchday readiness.')}finally{setBusy(false)}};
 const updateStatus=async()=>{if(!selected||!canManage)return;setBusy(true);try{const r=await api.post('/api/matchday/status',{fixtureId:selected.id,status});setData(d=>({...d,fixtures:d.fixtures.map(f=>f.id===selected.id?r.data:f)}));setNotice(`Match status set to ${status}.`)}catch{setNotice('Could not update the match status.')}finally{setBusy(false)}};
 const saveResult=async()=>{if(!selected)return;const home=Number(scores.home),away=Number(scores.away);if(!Number.isInteger(home)||!Number.isInteger(away)||home<0||away<0){setNotice('Enter whole-number scores for both teams.');return}setBusy(true);try{const r=await api.put(`/api/fixtures/${selected.id}`,{homeScore:home,awayScore:away,status:'completed',matchdayStatus:'Full time'});setData(d=>({...d,fixtures:d.fixtures.map(f=>f.id===selected.id?r.data:f)}));setNotice('Full-time result saved and standings recalculated.')}catch{setNotice('Could not save the result.')}finally{setBusy(false)}};
 return <><section className='page-header'><div><p className='eyebrow'>LEAGUE CONTROL</p><h1>Matchday Command Centre</h1><p className='muted'>Control confirmed fixtures, readiness, officials, team sheets, live status, results and exceptions from one workspace.</p></div><span className='status green'><Radio size={13}/> Realtime</span></section>
 <section className='stats-grid'><Stat icon={<CalendarDays/>} label='Active fixtures' value={`${fixtures.length}`} detail='current matchday queue'/><Stat icon={<Check/>} label='Confirmed' value={`${fixtures.filter(f=>f.matchdayStatus==='Confirmed').length}`} detail='ready for play'/><Stat icon={<Shield/>} label='Exceptions' value={`${exceptions.length}`} detail='requiring attention'/><Stat icon={<Flag/>} label='Post-match events' value={`${data.performanceCount}`} detail={`${data.disciplineCount} discipline records`}/></section>
 <div className='command-layout'><div className='card command-fixtures'><div className='card-head'><div><span className='label'>FIXTURE QUEUE</span><h2>Today & upcoming</h2></div><Clock3 size={19}/></div>{fixtures.map(f=><button key={f.id} className={`command-fixture ${selected?.id===f.id?'selected':''}`} onClick={()=>setSelectedId(f.id)}><span className='command-date'>{f.date}<small>{f.time}</small></span><span className='command-match'><b>{f.home}</b><span>vs</span><b>{f.away}</b><small>{f.venue}</small></span><span className={`status ${f.matchdayStatus==='Confirmed'?'green':f.matchdayStatus==='Live'?'blue':'amber'}`}>{f.matchdayStatus||'Planned'}</span></button>)}{!fixtures.length&&<div className='empty-state'><h3>No active fixtures</h3><p>Completed fixtures are in the results archive.</p></div>}</div>
 {selected&&<div className='card command-detail'><div className='card-head'><div><span className='label'>SELECTED MATCH</span><h2>{selected.home} vs {selected.away}</h2><p className='muted'>{selected.date} · {selected.time} · {selected.venue}</p></div><span className='status green'>{selected.matchdayStatus||'Planned'}</span></div>
 <div className='readiness-grid'><CheckRow label='Venue ready' checked={ready.venueReady} onChange={v=>setReady(r=>({...r,venueReady:v}))} icon={<Home/>}/><CheckRow label='Officials ready' checked={ready.officialsReady} onChange={v=>setReady(r=>({...r,officialsReady:v}))} icon={<Shield/>}/><CheckRow label='Team sheet ready' checked={ready.teamSheetReady} onChange={v=>setReady(r=>({...r,teamSheetReady:v}))} icon={<ClipboardCheck/>}/><CheckRow label='Result ready' checked={ready.resultReady} onChange={v=>setReady(r=>({...r,resultReady:v}))} icon={<Trophy/>}/></div>
 <textarea className='command-notes' value={ready.notes} onChange={e=>setReady(r=>({...r,notes:e.target.value}))} placeholder='Operational notes...'/><div className='command-actions'><button className='primary' disabled={busy||!canManage} onClick={saveReadiness}><Check size={15}/>Save readiness</button><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className='ghost' disabled={busy||!canManage} onClick={updateStatus}><Radio size={15}/>Update status</button></div>
 <div className='command-columns'><div><span className='label'>OFFICIALS</span>{appointments.length?appointments.map(a=><div className='command-row' key={a.id}><Shield size={15}/><span><b>{a.role}</b><small>{a.officialId}</small></span><span className='status green'>{a.status}</span></div>):<div className='empty-inline'>No official appointment linked.</div>}</div><div><span className='label'>TEAM SHEET</span>{sheet?<div className='command-row'><ClipboardCheck size={15}/><span><b>{sheet.formation}</b><small>Captain {sheet.captainRef} · {sheet.attendance.length} present</small></span><span className='status green'>Saved</span></div>:<div className='empty-inline'>No digital team sheet linked.</div>}</div></div>
 <div className='result-box'><div><span className='label'>RESULT CENTRE</span><h3>{selected.status==='completed'?'Final result':'Full-time result'}</h3></div><div className='score-fields'><input type='number' min='0' value={scores.home} onChange={e=>setScores(s=>({...s,home:e.target.value}))} placeholder='Home'/><b>—</b><input type='number' min='0' value={scores.away} onChange={e=>setScores(s=>({...s,away:e.target.value}))} placeholder='Away'/><button className='primary small' disabled={busy} onClick={saveResult}>Save result</button></div></div></div>}</div>
 <div className='dashboard-grid lower'><div className='card'><div className='card-head'><div><span className='label'>EXCEPTION QUEUE</span><h2>What needs attention</h2></div></div>{exceptions.slice(0,8).map(f=><div className='exception-row' key={f.id}><div><b>{f.home} vs {f.away}</b><small>{f.date} · {!f.matchdayStatus||f.matchdayStatus==='Planned'?'Matchday not confirmed':'Review operational readiness'}</small></div><span className='status amber'>Action</span></div>)}{!exceptions.length&&<div className='empty-state'><h3>All active fixtures are controlled</h3><p>No operational exceptions are visible.</p></div>}</div><div className='card'><div className='card-head'><div><span className='label'>INTEGRATED PIPELINE</span><h2>After the whistle</h2></div><Trophy size={19}/></div><Queue title='Result & standings' detail='Full-time scores recalculate the league table.' icon={<Trophy/>}/><Queue title='Performance' detail={`${data.performanceCount} events are in the performance ledger.`} icon={<Users/>}/><Queue title='Discipline' detail={`${data.disciplineCount} records are in the competition ledger.`} icon={<Shield/>}/><Queue title='Communications' detail='Operational updates remain in the league inbox.' icon={<Radio/>}/></div></div></>;
}
function CheckRow({label,checked,onChange,icon}:{label:string;checked:boolean;onChange:(v:boolean)=>void;icon:React.ReactNode}){return <button className={`readiness-row ${checked?'checked':''}`} onClick={()=>onChange(!checked)}><span className='readiness-icon'>{icon}</span><span>{label}</span><span className='readiness-check'>{checked?<Check size={14}/>:''}</span></button>}
function Stat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className='card stat'><div className='stat-icon'>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>}
function Queue({title,detail,icon}:{title:string;detail:string;icon:React.ReactNode}){return <div className='queue'><span className='queue-icon'>{icon}</span><span><b>{title}</b><small>{detail}</small></span></div>}
