import { useEffect, useRef, useState } from 'react';
import { api, ws } from './platformClient';
import { AlertTriangle, Check, Clock3, FileCheck2, LockKeyhole, RefreshCw, Shield, UserCheck } from 'lucide-react';

type Role = 'Supporter' | 'Manager' | 'Club' | 'LFA Admin';
type Player = { playerId:string; team:string; teamId:string; clubId:string; consentStatus:string; documentStatus:string; readiness:string };
type Case = { id:string; playerId:string; team:string; severity:string; status:string; category:string; ownerRole:string; createdAt:number };
type Data = { version:string; role:Role; scope:{leagueId?:string;clubId?:string;teamId?:string}; summary:{players:number;consentReady:number;documentsReady:number;openCases:number;criticalCases:number;exceptions:number}; players:Player[]; cases:Case[]; exceptions:Array<{id:string;playerId:string;type:string;severity:string;status:string}>; ownFamily:Array<{playerId:string;relationship:string;status:string;consentStatus:string;documentStatus:string}>; audit:Array<{id:string;action:string;targetType:string;targetId:string;role:string;createdAt:number}>; permissions:string[] };
const empty:Data={version:'14.0',role:'Supporter',scope:{},summary:{players:0,consentReady:0,documentsReady:0,openCases:0,criticalCases:0,exceptions:0},players:[],cases:[],exceptions:[],ownFamily:[],audit:[],permissions:[]};
export default function SafeguardingCompliance({setNotice}:{setNotice:(v:string)=>void}){
 const [data,setData]=useState<Data>(empty); const [loading,setLoading]=useState(false); const [playerId,setPlayerId]=useState(''); const [category,setCategory]=useState('Safeguarding concern'); const [severity,setSeverity]=useState('Medium'); const [note,setNote]=useState(''); const [caseId,setCaseId]=useState(''); const [caseStatus,setCaseStatus]=useState('Under Review'); const connRef=useRef<ReturnType<typeof ws.connect>|null>(null);
 const load=async()=>{setLoading(true);try{const r=await api.get('/api/safeguarding-compliance');setData(r.data||empty);if(!playerId&&r.data?.players?.length)setPlayerId(r.data.players[0].playerId)}catch{setNotice('Could not load safeguarding and compliance data.')}finally{setLoading(false)}};
 useEffect(()=>{void load();const conn=ws.connect();connRef.current=conn;conn.onMessage(msg=>{if(msg?.type==='entity.update'&&msg.payload?.entity_type==='safeguarding-compliance')setData(msg.payload.data as Data)});conn.ready.then(()=>{const id=conn.connectionId;if(id)void api.post('/api/subscriptions',{entity_type:'safeguarding-compliance',entity_id:'league',connection_id:id})}).catch(()=>undefined);return()=>conn.disconnect()},[]);
 const createCase=async()=>{if(!playerId||!note.trim()){setNotice('Select a player and enter a concise factual case note.');return}try{await api.post('/api/safeguarding-compliance/cases',{playerId,category,severity,note:note.trim()});setNote('');setNotice('Safeguarding case opened and audit recorded.');await load()}catch{setNotice('The safeguarding case could not be opened.')}};
 const updateCase=async()=>{if(!caseId){setNotice('Select a case first.');return}try{await api.put(`/api/safeguarding-compliance/cases/${caseId}`,{status:caseStatus});setNotice('Case status updated and audit recorded.');await load()}catch{setNotice('The case status could not be updated.')}};
 const updateDocument=async(id:string,status:string)=>{try{await api.post('/api/safeguarding-compliance/document-status',{playerId:id,status});setNotice('Document status updated.');await load()}catch{setNotice('Document status could not be updated.')}};
 const canManage=data.role==='LFA Admin'||data.role==='Club'; const statusClass=(v:string)=>v==='Ready'||v==='Resolved'||v==='Closed'?'green':v==='Critical'||v==='Action Required'?'red':'amber';
 return <><section className='page-header'><div><p className='eyebrow'>SAFEGUARDING & COMPLIANCE</p><h1>Command Centre 14.0</h1><p className='muted'>Consent readiness, document status, controlled safeguarding cases and auditable compliance controls.</p></div><button className='primary' onClick={()=>void load()}><RefreshCw size={15}/>{loading?'Refreshing':'Refresh'}</button></section>
 <section className='stats-grid'><Stat icon={<UserCheck/>} label='Consent ready' value={`${data.summary.consentReady}/${data.summary.players}`} detail='approved readiness status'/><Stat icon={<FileCheck2/>} label='Documents ready' value={`${data.summary.documentsReady}/${data.summary.players}`} detail='status only · contents protected'/><Stat icon={<AlertTriangle/>} label='Open cases' value={`${data.summary.openCases}`} detail={`${data.summary.criticalCases} critical`}/><Stat icon={<Shield/>} label='Exceptions' value={`${data.summary.exceptions}`} detail='items needing action'/></section>
 {data.role==='Supporter'?<section className='dashboard-grid'><div className='card'><span className='label'>MY FAMILY ACCESS</span><h2>Approved family status</h2><p className='muted small'>Only your approved family relationship and readiness status are shown.</p>{data.ownFamily.map(f=><div className='admin-row' key={f.playerId}><div><b>{f.playerId}</b><small>{f.relationship} · {f.status}</small></div><span className={`status ${statusClass(f.consentStatus)}`}>{f.consentStatus}</span><span className={`status ${statusClass(f.documentStatus)}`}>{f.documentStatus}</span></div>)}{!data.ownFamily.length&&<div className='empty-state'><h3>No approved family link</h3><p>Use Player & Family OS to request a guardian relationship.</p></div>}</div><div className='card'><span className='label'>PRIVACY BOUNDARY</span><h2>Protected by design</h2><Queue icon={<LockKeyhole/>} title='No case access' detail='Supporters cannot view or manage safeguarding cases.'/><Queue icon={<FileCheck2/>} title='Status, not contents' detail='Document readiness is shown without exposing document contents.'/><Queue icon={<Shield/>} title='Account scoped' detail='Family information is resolved from the signed-in account.'/></div></section>:<><section className='dashboard-grid'><div className='card'><div className='card-head'><div><span className='label'>COMPLIANCE REGISTER</span><h2>Player readiness</h2></div><LockKeyhole size={19}/></div>{data.players.map(p=><div className='admin-row' key={p.playerId}><div><b>{p.playerId}</b><small>{p.team} · {p.readiness}</small></div><span className={`status ${statusClass(p.consentStatus)}`}>{p.consentStatus}</span><span className={`status ${statusClass(p.documentStatus)}`}>{p.documentStatus}</span>{canManage&&<button className='ghost small' onClick={()=>void updateDocument(p.playerId,p.documentStatus==='Ready'?'Action required':'Ready')}>{p.documentStatus==='Ready'?'Flag':'Mark ready'}</button>}</div>)}{!data.players.length&&<div className='empty-state'><h3>No players in scope</h3><p>No player records are available for this role.</p></div>}</div><div className='card'><span className='label'>ROLE BOUNDARY</span><h2>{data.role} controls</h2>{data.permissions.map(p=><div className='permission-chip' key={p}><Check size={14}/>{p}</div>)}<div className='control-note'><LockKeyhole size={15}/><span>Server-side role and League / Club / Team scope controls this workspace.</span></div></div></section>
 <section className='dashboard-grid lower'><div className='card'><div className='card-head'><div><span className='label'>SAFEGUARDING CASE QUEUE</span><h2>Controlled cases</h2></div><Shield size={19}/></div>{data.cases.map(c=><button className={`tower-fixture ${caseId===c.id?'selected':''}`} key={c.id} onClick={()=>setCaseId(c.id)}><span><b>{c.playerId} · {c.category}</b><small>{c.team} · owner {c.ownerRole}</small></span><span className={`status ${statusClass(c.severity)}`}>{c.severity} · {c.status}</span></button>)}{!data.cases.length&&<div className='empty-state'><h3>No safeguarding cases in scope</h3><p>Authorized staff can open a controlled case when required.</p></div>}{canManage&&data.cases.length>0&&<div className='admin-grid'><select value={caseStatus} onChange={e=>setCaseStatus(e.target.value)}><option>Under Review</option><option>Action Required</option><option>Resolved</option><option>Closed</option></select><button className='primary' onClick={()=>void updateCase()}><Check size={15}/>Update selected case</button></div>}</div><div className='card'><span className='label'>COMPLIANCE EXCEPTIONS</span><h2>Needs attention</h2>{data.exceptions.map(x=><div className='exception-row' key={x.id}><AlertTriangle size={15}/><div><b>{x.playerId} · {x.type}</b><small>{x.severity} · {x.status}</small></div></div>)}{!data.exceptions.length&&<div className='empty-state'><h3>Compliance clear</h3><p>No outstanding exception flags are in your scope.</p></div>}</div></section>
 {canManage&&<section className='card announcement'><span className='label'>CONTROLLED CASE ENTRY</span><h2>Open a safeguarding case</h2><p className='muted small'>Keep notes factual and minimal. Do not enter medical details, contact information or unnecessary sensitive data.</p><div className='admin-grid'><select value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value=''>Select player</option>{data.players.map(p=><option key={p.playerId} value={p.playerId}>{p.playerId} · {p.team}</option>)}</select><select value={category} onChange={e=>setCategory(e.target.value)}><option>Safeguarding concern</option><option>Consent exception</option><option>Document exception</option><option>Matchday safeguarding flag</option></select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option>Low</option><option>Medium</option><option>High</option><option>Critical</option></select></div><textarea value={note} onChange={e=>setNote(e.target.value.slice(0,500))} placeholder='Minimal factual case note (500 characters max)'/><button className='primary' onClick={()=>void createCase()}><AlertTriangle size={15}/>Open controlled case</button></section>}
 <section className='card'><div className='card-head'><div><span className='label'>AUDIT TRAIL</span><h2>Recent controlled actions</h2></div><Clock3 size={19}/></div>{data.audit.slice(0,10).map(a=><div className='admin-row' key={a.id}><div><b>{a.action}</b><small>{a.targetType} · {a.targetId}</small></div><span className='status blue'>{a.role}</span></div>)}{!data.audit.length&&<div className='empty-state'><h3>No controlled actions yet</h3><p>Sensitive changes will appear here with role and timestamp.</p></div>}</section></>}
 </>;
}
function Stat({icon,label,value,detail}:{icon:React.ReactNode;label:string;value:string;detail:string}){return <div className='card stat'><div className='stat-icon'>{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></div>}
function Queue({icon,title,detail}:{icon:React.ReactNode;title:string;detail:string}){return <div className='queue'><span className='queue-icon'>{icon}</span><span><b>{title}</b><small>{detail}</small></span></div>}
